### ISSUE TITLE
Checking the version numbers

### ISSUE THREAD

**Issue by sangwinc** [mathinstitut/goemaxima#11]
Would it be helpful if STACK checked the Maxima version number.

For example, it would be "easy" to check if the STACK plugin version number
https://github.com/maths/moodle-qtype_stack/blob/master/version.php#L27
actually matches the maxima code version number 
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L3442

Currently this is only done on the "heathcheck" page.  We could do this check on every call to the CAS, without significant loss of performance.  E.g. putting a check in at a lowish level such as
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/cassession2.class.php#L410

This would then signal an error on every Maxima call (!) and users would know they need to upgrade their Maxima pool.  I get support requests because people haven't upgraded their Maxima and something has broken....

This requires no changes here, but would only affect the STACK plugin itself.  @aharjula Do you have any comments?
Chris

**Comment by aharjula** [comment]
Chris,

Given that we already have the version in every session, which you can confirm by looking at the CAS-cache and at this line:

https://github.com/maths/moodle-qtype_stack/blob/390aa65db79c7a73995d14063ccc59b70f638e99/stack/cas/cassession2.class.php#L334

You only need to do the check and generate that error. I have nothing against this. To me, it makes sense to either work when we have the correct version or to fail obviously, if the version does not match.

**Comment by Lennart-Kramer** [comment]
I see you resolved this already, but thanks anyway for opening the issue. The version mismatch warning in the healthcheck page was very buried, so this is a nice addition.

**Comment by sangwinc** [comment]
I didn't really anticipate the kind of distributed service you have, and when the person upgrading the maxima images is also upgrading the moodle/ilias plugin then the healthcheck is adequate.  We do now need this.

Perhaps you could checkout the "dev" branch somewhere you can test it and confirm this is a useful addition?

**Comment by Lennart-Kramer** [comment]
Tested it with the dev branch, works great. It shows up when answering questions and running question tests, so it should hopefully be hard to miss this.
