### ISSUE TITLE
Error trying ./buildimage.sh 2023060500

### ISSUE THREAD

**Issue by guaracheitor** [mathinstitut/goemaxima#13]
Hi, and thanks for this interesting project.

When I try to build goemaxima docker image I receive this error:

 => ERROR [10/12] COPY ./bin/web /opt/maxima/bin/goweb                                                                                                                                   0.0s
------
 > [10/12] COPY ./bin/web /opt/maxima/bin/goweb:
------
failed to compute cache key: "/bin/web" not found: not found

Some hint?

Best Regards,
Inti

**Comment by Lennart-Kramer** [comment]
Have you run `buildweb.sh` to build the server executable before building the image (the server executable is built outside the docker image right now for Reasons)? Did it throw an error?

**Comment by guaracheitor** [comment]
No, I haven't. I will try then.

Thanks!

**Comment by guaracheitor** [comment]
Hi, 
buildweb.sh worked great, but image creation process is stuck now with this error:
#8 485.2 make[1]: *** [../asdf-module.mk:41: test] Error 1

I would like to create the image in order to try to install goemaxima in a Debian server without Docker.

**Comment by Lennart-Kramer** [comment]
Ok, is there a reason you want to run it outside a container? I can't really recommend running it outside a container, but if you want to go through that effort, I can't stop you.
The buildimage.sh script builds a docker image, but you want to install it directly on the server, so do you actually want to do that?

Also for the error, I think I'll need a couple dozen lines before that to know what went wrong.

**Comment by guaracheitor** [comment]
Hi Lennart-Krammer, 
I prefer  to use docker too, but for now my sysadmin doesn't let me use it in production. In order to show him goemaxima I need to make it work in a debian11 server first. I hope to use docker+kubernetes at the end.

I have copied image:/usr/local and image:/opt to my debianbox, but could you tell me what else I need to set to achieve this goal?
Thanks for your help!

**Comment by guaracheitor** [comment]
On the other hand,   this are the last lines of my build attempt:

#8 484.1 28: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:TEST-OP "sb-simd") [fast-method]
#8 484.1 29: (ASDF/OPERATE:TEST-SYSTEM "sb-simd")
#8 484.1 30: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/INTERFACE::TEST-ASDF-CONTRIB "sb-simd") #<NULL-LEXENV>)
#8 484.1 31: (EVAL (ASDF/INTERFACE::TEST-ASDF-CONTRIB "sb-simd"))
#8 484.1 32: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "../asdf-stub.lisp") (:EVAL . "(asdf::test-asdf-contrib \"sb-simd\")")))
#8 484.1 33: (SB-IMPL::TOPLEVEL-INIT)
#8 484.1 34: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
#8 484.1 35: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
#8 484.1 36: (SB-IMPL::%START-LISP)
#8 484.1 
#8 484.1 unhandled condition in --disable-debugger mode, quitting
#8 484.1 ; 
#8 484.1 ; compilation unit aborted
#8 484.1 ;   caught 1 fatal ERROR condition
#8 484.1 make[1]: *** [../asdf-module.mk:41: test] Error 1
#8 484.1 make[1]: Leaving directory '/opt/src/sbcl-sbcl-2.2.6/contrib/sb-simd'
#8 484.1 make: Leaving directory '/opt/src/sbcl-sbcl-2.2.6/contrib'
#8 484.1 
#8 484.1 WARNING! Some of the contrib modules did not build successfully or pass
#8 484.1 their self-tests. Failed contribs:"
#8 484.1   sb-simd
------
executor failed running [/bin/sh -c bash /buildscript.sh]: exit code: 1

**Comment by Lennart-Kramer** [comment]
The failing command seems to be a test for sbcl failing. The SIMD makes me think this could be a CPU specific issue?

For installing it (I might be missing steps since I didn't try installing it myself)
1. The other program that needs to be installed is gnuplot, you can probably just install it with `apt-get install gnuplot`.
2. Then, since goemaxima executes each query as its own user for isolation purposes, you're going to need to create 32 users from `maxima-1` to `maxima-32` by doing `for i in 32; do useradd -M "maxima-$i"; done`. This doesn't create home directories, it's just necessary for mapping usernames to user ids and to make sure that the user is not used by anything else.
3. There also needs to be a `goemaxima-nobody` user (the reasons for this are fairly technical, but it's needed for killing all processes of a `maxima-$i` user). Create it with `useradd -M goemaxima-nobody`.
4. The environment variables
    ```
    ENV GOEMAXIMA_LIB_PATH=/opt/maxima/assets/maximalocal.mac
    ENV GOEMAXIMA_NUSER=32
    ```
    must be set.

**Comment by Lennart-Kramer** [comment]
By the way, another way to not use docker would be to just extract the whole image and, at the extracted root directory as root, execute
```
mount -t devtmpfs none dev
mount -t proc none proc
mount -t sysfs none sys
unshare -p --fork chroot . tini -- /opt/maxima/bin/goweb /opt/maxima/bin/maxima-optimised
```
This just makes a chroot with its own pid namespace which is basically a subset of what docker does.

**Comment by guaracheitor** [comment]
It seems to work from goemaxima server:
```
maxima@maxima:~/goemaxima$ curl localhost:8080/maxima
Hostname: maxima, version: 1.1.9

maxima@maxima:~$ sudo netstat -ano |grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      off (0.00/0/0)

```

But I can't see it from moodle server:
```
maxima@moodle:~$ curl http://maxima:8080/maxima
curl: (7) Failed to connect to maxima port 8080: No existe ninguna ruta hasta el `host'
maxima@moodle:~$ ping maxima
PING maxima (10.0.2.12) 56(84) bytes of data.
64 bytes from maxima (10.0.2.12): icmp_seq=1 ttl=64 time=1.02 ms
64 bytes from maxima (10.0.2.12): icmp_seq=2 ttl=64 time=1.17 ms
64 bytes from maxima (10.0.2.12): icmp_seq=3 ttl=64 time=0.590 ms
^C
--- maxima ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 0.590/0.925/1.167/0.244 ms
```
TNX for your help!

**Comment by Lennart-Kramer** [comment]
Hmm, I don't think I can do much from my side as this seems to be a network issue. Is there maybe a firewall rule that blocks port 8080?

**Comment by guaracheitor** [comment]
I think that the problem comes that goweb start at tcp6 address and moodle server can't see it :(
tcp6       0      0 :::8080                 :::*                    LISTEN      1127/goweb          

When starts from docker it is at tcp4 port:
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -

**Comment by Lennart-Kramer** [comment]
Normally, binding to tcp6-only will make linux translate ipv4 addresses into ipv4-mapped ipv6 addresses. This is enabled if `sysctl net.ipv6.bindv6only` returns 0. And I tried it outside of docker on an ipv4-only network and it seemed to work, so I'm not sure this is the problem.

**Comment by guaracheitor** [comment]
There is no way, locally works ok but not over LAN. ChatGPT says that is caused by isolation. I'll ask help at Moodle Forum.
Thanks a lot for your help!

**Comment by guaracheitor** [comment]
Solved! You were right, I've resintalled iptables and it is working now.
Tnx again!

**Comment by Lennart-Kramer** [comment]
Nice to see it working now
