### ISSUE TITLE
Manifest for Version 202312110 unknown

### ISSUE THREAD

**Issue by StefanGoeb** [mathinstitut/goemaxima#15]
user@ubuntu:~/goemaxima# export STACKMAXIMA_VERSION=2023121100
user@ubuntu:~/goemaxima# docker-compose up -d
Creating network "goemaxima_default" with the default driver
Pulling maxima (mathinstitut/goemaxima:2023121100-latest)...
ERROR: manifest for mathinstitut/goemaxima:2023121100-latest not found: manifest unknown: manifest unknown

It works for the previous versions, but not for the newest one. Any ideas, whats going on? Thanks and kind regards.

**Comment by Lennart-Kramer** [comment]
Sorry about that, I uploaded the files for the new version yesterday but haven't had time to actually push the new tag to upload the docker image.
It should be fixed now.
