### ISSUE TITLE
LISP Error running the docker image

### ISSUE THREAD

**Issue by oreimerEAH** [mathinstitut/goemaxima#16]
Hi, I'm trying to run the latest maxima docker (2023102700, 2023121100, 2024012900).  On a CentOS 7 machine.
Unfortunately I get the following error: 

2024/02/07` 11:10:25 Info: Maximum number of processes is 32
2024/02/07 11:10:25 Info: Ready process queue length is 3
2024/02/07 11:10:25 Info: goe handler started
2024/02/07 11:10:25 Debug: load("/opt/maxima/assets/maximalocal.mac")$
2024/02/07 11:10:25 Debug: Loaded file
2024/02/07 11:10:25 Debug: Attempting to find out readiness of mother process
Maxima encountered a Lisp error:
 
Could not create new OS thread.
Automadebugger invoked on a SB-INT:SIMPLE-CONTROL-ERROR @52A0086D in thread
t#<THREAD "main thread" RUNNING {1002B40003}>:
ically conti  attempt to THROW to a tag that does not exist: RETURN-FROM-DEBUGGER
nuing.
To enable the Lisp debugger set *debugger-hook* to nil.
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.
(THROW)
0] 
WARNING: Starting a poll(2) without a timeout while interrupts are disabled.
2024/02/07 11:10:35 Fatal: Could not start the mother process, timed out

The version 2023072101 version running fine.

Regards
Oliver

**Comment by Lennart-Kramer** [comment]
The images from 2023102700 on use debian 12 which uses some syscalls not supported by seccomp on older docker versions. I just spun up a centos 7 vm and it used a very old docker version when using `yum install docker` and I could reproduce the issue.

Using a newer version (following https://docs.docker.com/engine/install/centos) resolved the problem for me.

**Comment by oreimerEAH** [comment]
Thank you. This fixed the problem for me.
