### ISSUE TITLE
Running mathinstitut/goemaxima:2023121100-latest on podman fails

### ISSUE THREAD

**Issue by slaudel** [mathinstitut/goemaxima#18]
We were running goemaxima on podman successfully for a while now, but since upgrading to Release **2023102700-latest** it does not work anymore.

We run it on AlmaLinux 8.9 with podman 3.0.1, SELinux enabled but permissive mode:
```
/usr/bin/podman run --rm --name maxima -p 8765:8080/tcp --tmpfs /tmp -e GOEMAXIMA_DEBUG=1 docker.io/mathinstitut/goemaxima:2023121100-latest

2024/03/28 06:40:44 Info: Maximum number of processes is 32
2024/03/28 06:40:44 Info: Ready process queue length is 3
2024/03/28 06:40:44 Info: goe handler started
2024/03/28 06:40:44 Debug: load("/opt/maxima/assets/maximalocal.mac")$
2024/03/28 06:40:44 Debug: Loaded file
2024/03/28 06:40:44 Debug: Attempting to find out readiness of mother process

debugger invoked on a SB-INT:SIMPLE-CONTROL-ERROR @52A0086D in thread
#<THREAD "main thread" RUNNING {1002B40003}>:
  attempt to THROW to a tag that does not exist: RETURN-FROM-DEBUGGER
2024/03/28 06:40:54 Fatal: Could not start the mother process, timed out
```
When starting the release used before (**2023072101-latest**) it still works. So somethings seems to have changed inside the container which leads to this problem.

**Comment by Lennart-Kramer** [comment]
This is probably the same underlying issue as with https://github.com/mathinstitut/goemaxima/issues/16: the new image uses debian 11 as base image, which is incompatible with older docker/podman versions.
Is it possible for you to use a newer podman version?

**Comment by Lennart-Kramer** [comment]
Pinging again since the previous message was probably lost because it was posted right before the Easter weekend. Did upgrading work, or is there something preventing the upgrade?

**Comment by slaudel** [comment]
I couldn't test this, because we have another container running on the same podman install. We are running on podman 3.0.1.
But for us the problem is resolved by moving goemaxima into our new kubernetes cluster.

**Comment by Lennart-Kramer** [comment]
Alright, I'm closing this then
