### ISSUE TITLE
Compilation error in maxima_fork.c with gcc 11.2

### ISSUE THREAD

**Issue by lmocofan** [mathinstitut/goemaxima#5]
Compiling maxima_fork.c with gcc 11.2 throws an error.

OS: Alpine Linux 3.16
GCC: 11.2.1 20220219
Error:
goemaxima/src/maxima_fork.c: In function 'fork_new_process':
goemaxima/src/maxima_fork.c:168:23: error: assignment of read-only variable 'stdin'
  168 |                 stdin = new_stdin;

**Comment by Lennart-Kramer** [comment]
I have updated the code to use `freopen(3)` instead of assigning `stdin`. While latter is explicitly supported by glibc, the same is apparently not true of musl (which I assume alpine linux uses). In any case, `freopen(3)` is actually made for just this use case so this solution is actually better.

**Comment by Lennart-Kramer** [comment]
Also, just out of curiosity, is there a reason you are compiling this yourself/not using the Dockerfile from this repo?

**Comment by lmocofan** [comment]
Thank you very much for fixing this. There are couple of reasons for using Alpine Linux:
1. All of our images are based on Alpine Linux.
2. Shorter build time, 52s on Alpine vs 2m36 on Debian (we created Alpine packages for SBCL and Maxima).
3. Smaller image, 355MB on Alpine vs 649MB on Debian.

**Comment by Lennart-Kramer** [comment]
Thanks for the info, I'm closing this then.
