### ISSUE TITLE
Should we fetch SBCL from GitHub rather than SourceForge?

### ISSUE THREAD

**Issue by timhunt** [mathinstitut/goemaxima#8]
Currently, the build script fetches the SBCL code from SourceForge (https://github.com/mathinstitut/goemaxima/blob/7fc1653c4306ea2a9f0fa9298c2f7f131dd8e081/buildscript.sh#L19).

We had a nastly scare this afternoon, because a whole bunch for release files disappears from SourceForge, so our build broke. (See https://sourceforge.net/p/sbcl/mailman/sbcl-help/?viewmonth=202301&viewday=19 - the files are back now, so it must have been some sort of temporary glitch.)

Anyway, from that I discovered that SBCL is also avaialble on GitHub at https://github.com/sbcl/sbcl/releases, so we could be downloading the source from URLs like https://github.com/sbcl/sbcl/archive/refs/tags/sbcl-2.2.6.tar.gz, if we thought GitHub was likely to be more reliable than SourceForge.

Just a suggestion for you to consider. Thanks for continuing to maintain goemaxima.

**Comment by Lennart-Kramer** [comment]
That's a good idea, SourceForge downloads are also sometimes fairly slow for me, and for some reason it does 4 redirects before it starts downloading.

The tagged releases on GitHub don't contain binaries though, so I changed it to temporarily install Debian's SBCL for bootstrapping and uninstall it after the build, but I don't think that will cause problems.
